- opa/conversion.go
- opa/engine.go
- opa/function.go
- opa/rule.go
- opa/ruleset.go
This PR adds the `terraform.resources` function as a first step to support Terraform configuration. This allows us to write policies like the following:
```rego
package tflint
deny_not_snake_case[issue] {
resources := terraform.resources("aws_instance")
not regex.match("^[a-z][a-z0-9]*(_[a-z0-9]+)*$", resources[i].name)
issue := {
"message": sprintf("%s is not snake case", [resources[i].name]),
"severity": "error",
"location": resources[i].decl_range
}
}
```
Issues are reported as follows:
```console
$ tflint
1 issue(s) found:
Error: main-v2 is not snake case (opa_deny_not_snake_case)
on main.tf line 1:
1: resource "aws_instance" "main-v2" {
Reference: /home/codespace/.tflint.d/policies/test.rego:3
```
Note that attributes in the body such as `instance_type` are not yet supported. To …
> Add `terraform.resources` function without schema

- go.mod
- opa/conversion.go
- opa/engine.go
- opa/function.go
This PR adds support for a schema argument to `terraform.resources()` function, allowing you to reference arbitrary attributes. This allows us to write policies like the following:
```rego
deny_t3_nano[issue] {
resources := terraform.resources("aws_instance", {"instance_type": "string"})
instance_type := resources[_].config.instance_type
instance_type.value == "t3.nano"
issue := {
"message": "t3.nano is not allowed",
"severity": "error",
"location": instance_type.range
}
}
```
Nested attributes can be referenced as follows:
```rego
deny_large_volume[issue] {
resources := terraform.resources("aws_instance", {"ebs_block_device": {"volume_size": "number"}})
volume_size := resources[_].config.ebs_block_device[_].config.volume_size
volume_size.value > 30
issue := {
"message": "Allowed volume …
```
> Add support for retrieving resources based on schema

- opa/engine.go
- opa/rule.go
Inspired by Conftest, instead of including the severity in the issue, the rule name controls the severity.
Not only "deny_" but also "violation_", "warn_", "notice_" are valid for the rule name. The "violation" is the same as "deny".
> Use rule name as severity

- opa/ruleset.go
This PR supports incremental rules by allowing duplicate rule names. This allows you to write queries like:
```rego
package tflint
deny_invalid_type[issue] {
resources := terraform.resources("aws_instance", {"instance_type": "string"})
instance_type := resources[_].config.instance_type
instance_type.value != "t2.micro"
issue := tflint.issue("t2.micro is only allowed", instance_type.range)
}
deny_invalid_type[issue] {
resources := terraform.resources("aws_instance", {"instance_type": "string"})
instance_type := resources[_].config.instance_type
instance_type.unknown == true
issue := tflint.issue("instance type is unknown, you need to add tflint-ignore annotation here", instance_type.range)
}
```
Note that if there are multiple rules, the issue reference will refer to the first line. For …
> Allow incremental rules

- opa/conversion.go
- opa/function.go
This PR exposes options to the `terraform.resources` function that control whether meta-arguments and dynamic blocks are expanded.
> Add an options argument to `terraform.resources`

- go.mod
- go.sum
- opa/config.go
- opa/ruleset.go
This PR allows changing the policy directory in various ways.
The first is the declaration in the config file. This allows different policies to be applied to each module when used with `--recursive`. For example:
```hcl
plugin "opa" {
enabled = true
policy_dir = "tflint/policies"
}
```
The second is environment variables. You can change the directory using `TFLINT_OPA_POLICY_DIR`.
The last is `./.tflint.d/policies` support. Similar to the plugin directory, if you have `.tflint.d/policies` locally, it will take precedence over `~/.tflint.d/policies`.
The priority is as follows:
1. `policy_dir` in a config file
2. `TFLINT_OPA_POLICY_DIR` environment variable
3. Current directory (`./.tflint.d/policies`)
4. Home directory (`~/.tflint.d/policies`)
> Make the policy dir configurable

- opa/conversion.go
This PR adds support for labeled blocks. Previously, the schema for `terraform.resources` intentionally did not take labeled blocks into account. This is because labeled blocks are not a common use case. See also https://github.com/hashicorp/terraform/issues/32180#issuecomment-1305984280
However, some reserved blocks (e.g. `dynamic`, `backend`) are labeled. The current mechanism cannot retrieve them, so a custom function must explicitly decode them.
To avoid this, we introduce the special keyword `__labels`. You can retrieve labeled blocks by declaring this as a block schema. Below is an example of retrieving dynamic blocks:
```rego
deny_dynamic_blocks[issue] {
resources := terraform.resources("*", {"dynamic": {"__labels": ["name"]}}, {"expand_mode": "none"})
dynamic := …
```
> Add support for labeled blocks

- opa/conversion.go
- opa/function.go
This PR adds more terraform functions. Below is a list of added functions:
- `terraform.data_sources`
- `terraform.module_calls`
- `terraform.providers`
- `terraform.settings`
- `terraform.variables`
- `terraform.outputs`
- `terraform.locals`
- `terraform.moved_blocks`
> Add more terraform functions

- README.md
- main.go
Support for dynamic blocks was added from v0.43, so to avoid confusion, set a constraint to only work with v0.43+.
> Require TFLint >=0.43.0

- opa/conversion.go
- opa/engine_test.go
- opa/functions.go
See also https://github.com/open-policy-agent/opa/issues/5582
Nested named types are not allowed in the compiler. This PR removes all named types.
> Remove named type

- opa/conversion.go
- opa/conversion_test.go
- opa/test_runner.go
- opa/test_runner_test.go
See https://github.com/terraform-linters/tflint-ruleset-opa/actions/runs/4651361434/jobs/8230916678
See https://github.com/terraform-linters/tflint-plugin-sdk/pull/239
TFLint v0.46 now allows marked values (sensitive values) to be transferred to plugins. In that case, evaluating a sensitive value will not return `tflint.ErrSensitive`, but rather the marked `cty.Value`.
`exprToJSON` tries to marshal `cty.Value` to JSON format, but it returns an error like the below when marshaling a marked value:
```
value has marks, so it cannot be serialized as JSON
```
This PR converts marked values to JSON in a different way to prevent this error.
> Fix internal marshal error of sensitive value

- docs/configuration.md
Fixes https://github.com/terraform-linters/tflint-ruleset-opa/issues/43
> docs: Clarify what `policy_dir` is relative to

- docs/functions.md
- integration/checks/.tflint.hcl
- integration/checks/main.tf
- integration/checks/policies/main.rego
- integration/checks/policies/main_test.rego
- integration/checks/result.json
- integration/checks/result_test.json
- integration/imports/.tflint.hcl
- integration/imports/main.tf
- integration/imports/policies/main.rego
- integration/imports/policies/main_test.rego
- integration/imports/result.json
- integration/imports/result_test.json
- integration/integration_test.go
- opa/functions.go
- opa/functions_test.go
See https://developer.hashicorp.com/terraform/language/import
See https://developer.hashicorp.com/terraform/language/checks
This PR adds new functions, `terraform.imports` and `terraform.checks`. These correspond to the `import` and `check` blocks introduced in Terraform v1.5.
The function interface and return values are pretty much the same as other functions, so there's no new functionality.
> Add `terraform.imports` and `terraform.checks` functions

- integration/data_sources/main.tf
- integration/data_sources/policies/main_test.rego
- integration/data_sources/result.json
- integration/data_sources/result_test.json
- opa/functions.go
- opa/functions_test.go
See also https://developer.hashicorp.com/terraform/language/checks
Terraform v1.5 now supports check blocks and scoped (nested) data sources.
This PR adds support for scoped data sources in the `terraform.data_sources` function.
> Add support for scoped data sources

- integration/resources/main.tf
See https://github.com/terraform-linters/tflint-ruleset-opa/actions/runs/7333894624/job/19969932237#step:7:59
TFLint v0.50 now automatically loads local modules, which causes some tests to fail. This PR fixes the E2E test resources to avoid these issues.
> Fix E2E tests failing with TFLint v0.50

- docs/functions.md
- integration/integration_test.go
- integration/removed/.tflint.hcl
- integration/removed/main.tf
- integration/removed/policies/main.rego
- integration/removed/policies/main_test.rego
- integration/removed/result.json
- integration/removed/result_test.json
- opa/functions.go
- opa/functions_test.go
See https://developer.hashicorp.com/terraform/language/resources/syntax#removing-resources
This PR adds a new `terraform.removed_blocks` function. This correspond to the `removed` blocks introduced in Terraform v1.7.
The function interface and return values are pretty much the same as other functions, so there's no new functionality.
> Add `terraform.removed_blocks` function

- docs/functions.md
- integration/ephemerals/.tflint.hcl
- integration/ephemerals/main.tf
- integration/ephemerals/policies/main.rego
- integration/ephemerals/policies/main_test.rego
- integration/ephemerals/result.json
- integration/ephemerals/result_test.json
- integration/integration_test.go
- opa/functions.go
- opa/functions_test.go
See https://developer.hashicorp.com/terraform/language/resources/ephemeral
This change adds a new `terraform.ephemeral_resources` function. This correspond to the ephemeral resources introduced in Terraform v1.10. The function interface and return values are pretty much the same as other functions, so there's no new functionality.
> Add `terraform.ephemeral_resources` function

- .github/workflows/release.yml
- CHANGELOG.md
- Makefile
- tools/release/go.mod
- tools/release/go.sum
- tools/release/main.go
See also https://github.com/terraform-linters/tflint/pull/1802
This PR automates the process required for releases.
Major processes like building binaries are already automated by GoReleaser, so the target here is creating commits for version upgrades. make release takes care of rewriting necessary files, creating commits, and pushing them to remotes on behalf of the maintainer.
> Add make release for release automation

- .github/workflows/build.yml
- .github/workflows/e2e.yml
- .github/workflows/goreleaser.yml
- .github/workflows/release.yml
See also https://www.wiz.io/blog/new-github-action-supply-chain-attack-reviewdog-action-setup
This PR makes GitHub Actions hash-pinned to reduce the risk of similar incidents.
Run `pinact run` with v1.4.0.
https://github.com/suzuki-shunsuke/pinact
> Pin GitHub Action versions

- tools/release/main.go
Potential fix for [https://github.com/terraform-linters/tflint-ruleset-opa/security/code-scanning/4](https://github.com/terraform-linters/tflint-ruleset-opa/security/code-scanning/4)
To fix the issue, the dot (`.`) in the regular expression should be escaped to ensure it matches a literal dot rather than any character. This can be done by replacing `.` with `\.`. Additionally, using a raw string literal (enclosed in backticks) for the regular expression can improve readability and avoid the need to double-escape backslashes.
The updated regular expression will be:
```
`github\.com/terraform-linters/tflint-plugin-sdk v(.+)`
```
This ensures that the pattern matches only the intended domain `github.com` and not any other unintended strings.
---
_Suggested fixes powered by Copilot Autofix. …
> Potential fix for code scanning alert no. 4: Incomplete regular expression for hostnames

- .github/workflows/build.yml
- .github/workflows/e2e.yml
- .github/workflows/goreleaser.yml
Fix actions/missing-workflow-permissions in Code Scanning alerts
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/terraform-linters/tflint-ruleset-opa/pull/151?shareId=b4a5e033-4894-4312-a0f4-f401c499f4d8).
> Set workflow permissions explicitly

- .goreleaser.yml
noticed this when working in a fork of the original project. The gorelease pipelines have been hard coded with the github repo owner and project name. 
This small change will allow others to run the actions(un modified) if they decide to fork the project and it also decouples the code base from platform if author ever decides to move the code or rename the repo
According to [GoReleaser](https://goreleaser.com/customization/release/), 
```
release:
```
> Decoupling the gorelease release pipeline 

- docs/functions.md
- docs/schema.md
- examples/enforce_tags_ignore/.tflint.d/policies/tags.rego
- examples/enforce_tags_ignore/.tflint.d/policies/tags_test.rego
- examples/enforce_tags_ignore/.tflint.hcl
- examples/enforce_tags_ignore/README.md
- examples/enforce_tags_ignore/main.tf
- integration/expr_without_eval/.tflint.hcl
- integration/expr_without_eval/main.tf
- integration/expr_without_eval/policies/main.rego
- integration/expr_without_eval/policies/main_test.rego
- integration/expr_without_eval/result.json
- integration/expr_without_eval/result_test.json
- integration/integration_test.go
- opa/conversion.go
- opa/conversion_test.go
- opa/functions.go
- opa/functions_test.go
Fixes https://github.com/terraform-linters/tflint-ruleset-opa/issues/165
This PR adds the `expr` type as a schema type. The `expr` type differs from other types in that they do not immediately evaluate a value but instead return an expression structure. For example:
```hcl
variable "instance_type" {
default = "t2.micro"
}
resource "aws_instance" "main" {
instance_type = var.instance_type
}
```
```rego
terraform.resources("aws_instance", {"instance_type": "string"}, {})
```
```json
[
{
"type": "aws_instance",
"name": "main",
"config": {
"instance_type": {
"value": "t2.micro",
"unknown": false,
"sensitive": false,
"ephemeral": false,
"range": {...}
}
},
"decl_range": {...}
}
]
```
```rego
terraform.resources("aws_instance", {"instance_type": "expr"}, {})
```
```json
[
{
"type": …
```
> Add "expr" type as a schema type
